server:
  port: 8084
spring:
  application:
    name: notification
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/notification
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://192.168.99.100:9411/
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka